language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - >
    echo;
    echo "Running unit tests";
    mkdir -p build/logs;
    if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; else PHPUNIT_FLAGS=""; fi ;
    php vendor/bin/phpunit --colors $PHPUNIT_FLAGS ;
